// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: shared.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Language int32

const (
	Language_ZH_CN Language = 0
	Language_EN_US Language = 1
	Language_JA_JP Language = 2
	Language_KO_KR Language = 3
	Language_OTHER Language = 4
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "ZH_CN",
		1: "EN_US",
		2: "JA_JP",
		3: "KO_KR",
		4: "OTHER",
	}
	Language_value = map[string]int32{
		"ZH_CN": 0,
		"EN_US": 1,
		"JA_JP": 2,
		"KO_KR": 3,
		"OTHER": 4,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{0}
}

type Server int32

const (
	Server_CN Server = 0
	Server_US Server = 1
	Server_JP Server = 2
	Server_KR Server = 3
)

// Enum value maps for Server.
var (
	Server_name = map[int32]string{
		0: "CN",
		1: "US",
		2: "JP",
		3: "KR",
	}
	Server_value = map[string]int32{
		"CN": 0,
		"US": 1,
		"JP": 2,
		"KR": 3,
	}
)

func (x Server) Enum() *Server {
	p := new(Server)
	*p = x
	return p
}

func (x Server) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Server) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[1].Descriptor()
}

func (Server) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[1]
}

func (x Server) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Server.Descriptor instead.
func (Server) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{1}
}

type MessageType int32

const (
	MessageType_ENTERED_SEARCH_RESULT   MessageType = 0
	MessageType_NAVIGATED               MessageType = 1
	MessageType_EXECUTED_ADVANCED_QUERY MessageType = 2
	MessageType_SERVER_ERRORED          MessageType = 64
	MessageType_SERVER_ACK              MessageType = 65
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "ENTERED_SEARCH_RESULT",
		1:  "NAVIGATED",
		2:  "EXECUTED_ADVANCED_QUERY",
		64: "SERVER_ERRORED",
		65: "SERVER_ACK",
	}
	MessageType_value = map[string]int32{
		"ENTERED_SEARCH_RESULT":   0,
		"NAVIGATED":               1,
		"EXECUTED_ADVANCED_QUERY": 2,
		"SERVER_ERRORED":          64,
		"SERVER_ACK":              65,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{2}
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=PenguinProbe.MessageType" json:"type,omitempty"`
	Language Language    `protobuf:"varint,2,opt,name=language,proto3,enum=PenguinProbe.Language" json:"language,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_ENTERED_SEARCH_RESULT
}

func (x *Meta) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ZH_CN
}

type Skeleton struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *Skeleton) Reset() {
	*x = Skeleton{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skeleton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skeleton) ProtoMessage() {}

func (x *Skeleton) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skeleton.ProtoReflect.Descriptor instead.
func (*Skeleton) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{1}
}

func (x *Skeleton) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type EnteredSearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are assignable to Id:
	//	*EnteredSearchResult_StageId
	//	*EnteredSearchResult_ItemId
	Id       isEnteredSearchResult_Id `protobuf_oneof:"id"`
	Query    string                   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Position uint32                   `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *EnteredSearchResult) Reset() {
	*x = EnteredSearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnteredSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnteredSearchResult) ProtoMessage() {}

func (x *EnteredSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnteredSearchResult.ProtoReflect.Descriptor instead.
func (*EnteredSearchResult) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{2}
}

func (x *EnteredSearchResult) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (m *EnteredSearchResult) GetId() isEnteredSearchResult_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *EnteredSearchResult) GetStageId() string {
	if x, ok := x.GetId().(*EnteredSearchResult_StageId); ok {
		return x.StageId
	}
	return ""
}

func (x *EnteredSearchResult) GetItemId() string {
	if x, ok := x.GetId().(*EnteredSearchResult_ItemId); ok {
		return x.ItemId
	}
	return ""
}

func (x *EnteredSearchResult) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *EnteredSearchResult) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type isEnteredSearchResult_Id interface {
	isEnteredSearchResult_Id()
}

type EnteredSearchResult_StageId struct {
	StageId string `protobuf:"bytes,2,opt,name=stageId,proto3,oneof"`
}

type EnteredSearchResult_ItemId struct {
	ItemId string `protobuf:"bytes,3,opt,name=itemId,proto3,oneof"`
}

func (*EnteredSearchResult_StageId) isEnteredSearchResult_Id() {}

func (*EnteredSearchResult_ItemId) isEnteredSearchResult_Id() {}

type ExecutedAdvancedQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta    *Meta                                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Queries []*ExecutedAdvancedQuery_AdvancedQuery `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *ExecutedAdvancedQuery) Reset() {
	*x = ExecutedAdvancedQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutedAdvancedQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedAdvancedQuery) ProtoMessage() {}

func (x *ExecutedAdvancedQuery) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedAdvancedQuery.ProtoReflect.Descriptor instead.
func (*ExecutedAdvancedQuery) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutedAdvancedQuery) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ExecutedAdvancedQuery) GetQueries() []*ExecutedAdvancedQuery_AdvancedQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type Navigated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *Meta  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Navigated) Reset() {
	*x = Navigated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Navigated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Navigated) ProtoMessage() {}

func (x *Navigated) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Navigated.ProtoReflect.Descriptor instead.
func (*Navigated) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{4}
}

func (x *Navigated) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Navigated) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ServerErrored struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=PenguinProbe.MessageType" json:"type,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ServerErrored) Reset() {
	*x = ServerErrored{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerErrored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerErrored) ProtoMessage() {}

func (x *ServerErrored) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerErrored.ProtoReflect.Descriptor instead.
func (*ServerErrored) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{5}
}

func (x *ServerErrored) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_ENTERED_SEARCH_RESULT
}

func (x *ServerErrored) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=PenguinProbe.MessageType" json:"type,omitempty"`
}

func (x *ServerACK) Reset() {
	*x = ServerACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerACK) ProtoMessage() {}

func (x *ServerACK) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerACK.ProtoReflect.Descriptor instead.
func (*ServerACK) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{6}
}

func (x *ServerACK) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_ENTERED_SEARCH_RESULT
}

type ExecutedAdvancedQuery_AdvancedQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId string   `protobuf:"bytes,1,opt,name=stageId,proto3" json:"stageId,omitempty"`
	ItemIds []string `protobuf:"bytes,2,rep,name=itemIds,proto3" json:"itemIds,omitempty"`
	Server  Server   `protobuf:"varint,3,opt,name=server,proto3,enum=PenguinProbe.Server" json:"server,omitempty"`
}

func (x *ExecutedAdvancedQuery_AdvancedQuery) Reset() {
	*x = ExecutedAdvancedQuery_AdvancedQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutedAdvancedQuery_AdvancedQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedAdvancedQuery_AdvancedQuery) ProtoMessage() {}

func (x *ExecutedAdvancedQuery_AdvancedQuery) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedAdvancedQuery_AdvancedQuery.ProtoReflect.Descriptor instead.
func (*ExecutedAdvancedQuery_AdvancedQuery) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ExecutedAdvancedQuery_AdvancedQuery) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *ExecutedAdvancedQuery_AdvancedQuery) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *ExecutedAdvancedQuery_AdvancedQuery) GetServer() Server {
	if x != nil {
		return x.Server
	}
	return Server_CN
}

var File_shared_proto protoreflect.FileDescriptor

var file_shared_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x50, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x22, 0x69, 0x0a, 0x04,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x50, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x50, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x08, 0x53, 0x6b, 0x65, 0x6c, 0x65,
	0x74, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x50, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0xab, 0x01, 0x0a, 0x13,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x50, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x07, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0x85, 0x02, 0x0a, 0x15, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x50, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x4b, 0x0a, 0x07, 0x71,
	0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x50,
	0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x64, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x2e, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x77, 0x0a, 0x0d, 0x41, 0x64, 0x76, 0x61,
	0x6e, 0x63, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x73, 0x12, 0x2c, 0x0a,
	0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x50, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4a, 0x04, 0x08, 0x04, 0x10,
	0x07, 0x22, 0x47, 0x0a, 0x09, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x65, 0x64, 0x12, 0x26,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x50,
	0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x58, 0x0a, 0x0d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x50, 0x65, 0x6e, 0x67,
	0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x43,
	0x4b, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x50, 0x65, 0x6e, 0x67, 0x75, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x2a, 0x41, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x09, 0x0a, 0x05,
	0x5a, 0x48, 0x5f, 0x43, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x5f, 0x55, 0x53,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4a, 0x41, 0x5f, 0x4a, 0x50, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x4b, 0x4f, 0x5f, 0x4b, 0x52, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45,
	0x52, 0x10, 0x04, 0x2a, 0x28, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x06, 0x0a,
	0x02, 0x43, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x53, 0x10, 0x01, 0x12, 0x06, 0x0a,
	0x02, 0x4a, 0x50, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x4b, 0x52, 0x10, 0x03, 0x2a, 0x78, 0x0a,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15,
	0x45, 0x4e, 0x54, 0x45, 0x52, 0x45, 0x44, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x52,
	0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x41, 0x56, 0x49, 0x47,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54,
	0x45, 0x44, 0x5f, 0x41, 0x44, 0x56, 0x41, 0x4e, 0x43, 0x45, 0x44, 0x5f, 0x51, 0x55, 0x45, 0x52,
	0x59, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x45, 0x44, 0x10, 0x40, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x52, 0x5f, 0x41, 0x43, 0x4b, 0x10, 0x41, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_proto_rawDescOnce sync.Once
	file_shared_proto_rawDescData = file_shared_proto_rawDesc
)

func file_shared_proto_rawDescGZIP() []byte {
	file_shared_proto_rawDescOnce.Do(func() {
		file_shared_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_proto_rawDescData)
	})
	return file_shared_proto_rawDescData
}

var file_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shared_proto_goTypes = []interface{}{
	(Language)(0),                 // 0: PenguinProbe.Language
	(Server)(0),                   // 1: PenguinProbe.Server
	(MessageType)(0),              // 2: PenguinProbe.MessageType
	(*Meta)(nil),                  // 3: PenguinProbe.Meta
	(*Skeleton)(nil),              // 4: PenguinProbe.Skeleton
	(*EnteredSearchResult)(nil),   // 5: PenguinProbe.EnteredSearchResult
	(*ExecutedAdvancedQuery)(nil), // 6: PenguinProbe.ExecutedAdvancedQuery
	(*Navigated)(nil),             // 7: PenguinProbe.Navigated
	(*ServerErrored)(nil),         // 8: PenguinProbe.ServerErrored
	(*ServerACK)(nil),             // 9: PenguinProbe.ServerACK
	(*ExecutedAdvancedQuery_AdvancedQuery)(nil), // 10: PenguinProbe.ExecutedAdvancedQuery.AdvancedQuery
}
var file_shared_proto_depIdxs = []int32{
	2,  // 0: PenguinProbe.Meta.type:type_name -> PenguinProbe.MessageType
	0,  // 1: PenguinProbe.Meta.language:type_name -> PenguinProbe.Language
	3,  // 2: PenguinProbe.Skeleton.meta:type_name -> PenguinProbe.Meta
	3,  // 3: PenguinProbe.EnteredSearchResult.meta:type_name -> PenguinProbe.Meta
	3,  // 4: PenguinProbe.ExecutedAdvancedQuery.meta:type_name -> PenguinProbe.Meta
	10, // 5: PenguinProbe.ExecutedAdvancedQuery.queries:type_name -> PenguinProbe.ExecutedAdvancedQuery.AdvancedQuery
	3,  // 6: PenguinProbe.Navigated.meta:type_name -> PenguinProbe.Meta
	2,  // 7: PenguinProbe.ServerErrored.type:type_name -> PenguinProbe.MessageType
	2,  // 8: PenguinProbe.ServerACK.type:type_name -> PenguinProbe.MessageType
	1,  // 9: PenguinProbe.ExecutedAdvancedQuery.AdvancedQuery.server:type_name -> PenguinProbe.Server
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_shared_proto_init() }
func file_shared_proto_init() {
	if File_shared_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skeleton); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnteredSearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutedAdvancedQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Navigated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerErrored); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutedAdvancedQuery_AdvancedQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_shared_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*EnteredSearchResult_StageId)(nil),
		(*EnteredSearchResult_ItemId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_goTypes,
		DependencyIndexes: file_shared_proto_depIdxs,
		EnumInfos:         file_shared_proto_enumTypes,
		MessageInfos:      file_shared_proto_msgTypes,
	}.Build()
	File_shared_proto = out.File
	file_shared_proto_rawDesc = nil
	file_shared_proto_goTypes = nil
	file_shared_proto_depIdxs = nil
}
